name: Telegram APK Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: cd bot && npm ci
        
      - name: Run Bot (Max 6 hours)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          ADMIN_TELEGRAM_ID: ${{ secrets.ADMIN_TELEGRAM_ID }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_OWNER: ${{ secrets.OWNER_GITHUB }}
          GITHUB_REPO: ${{ secrets.REPO_GITHUB }}
           LANDING_PAGE_URL: ${{ secrets.LANDING_PAGE_URL }}
           TRACKING_SECRET: ${{ secrets.TRACKING_SECRET }}
        run: node bot/bot.js
